name: my_application
description: My ToDo App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  path: ^1.8.2
  sqflite: ^2.2.8+4
  fluentui_icons: ^1.0.0
  flutter_native_splash: ^2.2.19
  audioplayers: ^4.1.0

flutter_native_splash:
  color: '#FFFFFF'
  #image: assets/images/splash_image.png
  android_12:
    color: '#FFFFFF'
    #image: assets/images/splash_image.png



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
